src/blog/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('favorites/', views.favorites),
    path('add-favorites/', views.add_favorite),
    path('delete-favorites/', views.delete_favorite),
    path('liked-recipes/', views.liked_recipes),
    path('like/', views.like),
    path('unlike/', views.unlike),
    path('delete-recipe/', views.delete_recipe),
    path('create-conversation', views.create_conversation),
    path('create-message', views.create_message),
    path('messages', views.get_messages),
]

src/blog/urls.py
from django.urls import path, include
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='home'),
    path('favorites/', views.home, name='favorites'),
    path('chat/', views.chat, name='chat'),
    path('profile/', views.profile, name='profile'),
    path('profile/<int:id>', views.profile, name='profile'),
    path('edit-profile/', views.edit_profile, name='edit-profile'),
    path('recipe/<int:id>/', views.recipe, name='recipe'),
    path('create-recipe/', views.create_recipe, name='create-recipe'),
    path('edit-recipe/<int:id>', views.edit_recipe, name='edit-recipe'),

    path('api/', include('blog.api.urls'))
]

src/foodhouse/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("landing.urls")),
    path('blog/', include('blog.urls', namespace='blog'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.db.models import JSONField

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Recipe(models.Model):

    DIFFICULTY_CHOICES = (
        ('easy', 'Easy'),
        ('normal', 'Normal'),
        ('hard', 'Hard'),
    )

    CATEGORY_CHOICES = (
        ('Breakfast', 'Breakfast'),
        ('Lunch', 'Lunch'),
        ('Snack', 'Snack'),
        ('Dinner', 'Dinner'),
    )

    title = models.CharField(max_length=200)
    body = models.TextField()
    duration = models.IntegerField(default=0)
    difficulty = models.CharField(
        max_length=10, choices=DIFFICULTY_CHOICES, default='easy')
    ingredients = JSONField(default=list, blank=True, null=True)
    categories = models.ManyToManyField(Category)
    banner = models.ImageField(
        upload_to='banners/', null=True, blank=True, default='default-recipe.png')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    likes_count = models.IntegerField(default=0)
    author = models.ForeignKey('landing.CustomUser', on_delete=models.CASCADE)

    class Meta:
        ordering = ('-updated_at', '-created_at',)

    def __str__(self):
        return f"{self.title}"


class Conversation(models.Model):
    participant1 = models.ForeignKey(
        'landing.CustomUser', on_delete=models.CASCADE, related_name='conversations_as_participant1')
    participant2 = models.ForeignKey(
        'landing.CustomUser', on_delete=models.CASCADE, related_name='conversations_as_participant2')
    messages = models.ManyToManyField(
        'Message', blank=True)


class Message(models.Model):
    sender = models.ForeignKey('landing.CustomUser', on_delete=models.CASCADE)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('created_at',)

src/blog/forms.py
from django import forms
from .models import Recipe


class CreateRecipeForm(forms.ModelForm):
    banner = forms.ImageField(
        required=False,
        widget=forms.FileInput(attrs={
            'class': 'hidden', 'accept': 'image/*', 'id': 'file-input'}),
    )

    title = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={
            'class': 'w-full focus:outline-none border-2 border-primary p-2 drop-shadow-md font-text',
            'placeholder': 'e.g: Burgers with fries',
            'id': 'title',
        })
    )

    body = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={
            'class': 'w-full focus:outline-none border-2 border-primary p-2 drop-shadow-md font-text resize-none',
            'id': 'body',
            'rows': 5,
        })
    )

    duration = forms.IntegerField(
        required=False,
        widget=forms.NumberInput(attrs={
            'class': 'w-full focus:outline-none border-2 border-primary p-2 drop-shadow-md font-text',
            'id': 'duration',
        })
    )

    difficulty = forms.ChoiceField(
        required=False,
        choices=Recipe.DIFFICULTY_CHOICES,
        widget=forms.Select(attrs={
            'class': 'w-full focus:outline-none border-2 border-primary p-2 drop-shadow-md font-text h-[43px]',
            'id': 'difficulty',
        })
    )

    categories = forms.MultipleChoiceField(
        required=False,
        choices=Recipe.CATEGORY_CHOICES,
        widget=forms.CheckboxSelectMultiple()
    )

    # Un json field
    ingredients = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={
            'class': 'h-0 w-0 p-0 border-0',
        })
    )

    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title:
            raise forms.ValidationError("This field is required")

        return title

    def clean_body(self):
        body = self.cleaned_data.get('body')
        if not body:
            raise forms.ValidationError("This field is required")

        return body

    def clean_duration(self):
        duration = self.cleaned_data.get('duration')
        if not duration:
            raise forms.ValidationError("This field is required")
        else:
            if not isinstance(duration, int):
                raise forms.ValidationError("This field must be a number")
            else:
                if duration < 0:
                    raise forms.ValidationError(
                        "Enter a positive number")

        return duration

    def clean_categories(self):
        categories = self.cleaned_data.get('categories')
        if not categories:
            raise forms.ValidationError("Select at least one category")

        return categories

    class Meta:
        model = Recipe
        fields = '__all__'
        exclude = ['author', 'likes_count', 'created_at', 'updated_at']

src/blog/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from blog.models import Recipe, Conversation, Message
from landing.models import CustomUser
from .serializers import MessageSerializer


@api_view(['GET'])
def favorites(request):
    try:
        user = request.user
        favorites_id = [favorite.id for favorite in user.favorites.all()]
        return Response({'status': 'success', 'favorites': favorites_id})
    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})


@api_view(['POST'])
def add_favorite(request):
    try:
        user = request.user
        recipe_id = request.data.get('recipe_id')
        user.favorites.add(recipe_id)
        return Response({'status': 'success'})
    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})


@api_view(['POST'])
def delete_favorite(request):
    try:
        user = request.user
        recipe_id = request.data.get('recipe_id')
        user.favorites.remove(recipe_id)
        return Response({'status': 'success'})
    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})


@api_view(['POST'])
def liked_recipes(request):
    try:
        user = request.user
        recipe_id = request.data.get('recipe_id')
        likes_id = [recipe.id for recipe in user.liked_recipes.all()]
        total = Recipe.objects.get(id=recipe_id).likes_count
        return Response({'status': 'success', 'liked_recipes': likes_id, 'total': total})
    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})


@api_view(['POST'])
def like(request):
    try:
        user = request.user
        recipe_id = request.data.get('recipe_id')
        user.liked_recipes.add(recipe_id)

        recipe = Recipe.objects.get(id=recipe_id)
        recipe.likes_count += 1
        recipe.save()

        return Response({'status': 'success'})
    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})


@api_view(['POST'])
def unlike(request):
    try:
        user = request.user
        recipe_id = request.data.get('recipe_id')
        user.liked_recipes.remove(recipe_id)

        recipe = Recipe.objects.get(id=recipe_id)
        if recipe.likes_count > 0:
            recipe.likes_count -= 1

        recipe.save()

        return Response({'status': 'success'})
    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})


@api_view(['DELETE'])
def delete_recipe(request):
    try:
        user = request.user
        recipe_id = request.data.get('recipe_id')
        recipe = Recipe.objects.get(id=recipe_id)
        if recipe.author == user:
            recipe.delete()
            return Response({'status': 'success'})
        else:
            return Response({'status': 'error', 'message': 'You are not the author of this recipe'})
    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})


@api_view(['POST'])
def create_conversation(request):
    try:
        user = request.user
        participant_id = request.data.get('participant_id')

        participant = CustomUser.objects.get(id=participant_id)

        conversations = Conversation.objects.filter(
            participant1=user, participant2=participant)
        if conversations:
            return Response({'status': 'success', 'conversation_id': conversations[0].id})
        else:
            conversation = Conversation.objects.create(
                participant1=user, participant2=participant)
            return Response({'status': 'success', 'conversation_id': conversation.id})

    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})


@api_view(['GET'])
def get_messages(request):
    try:
        user = request.user
        conversation_id = request.GET.get('conversation_id')
        conversation = Conversation.objects.get(id=conversation_id)

        messages = conversation.messages.all()
        serializer = MessageSerializer(messages, many=True)

        return Response({'status': 'success', 'messages': serializer.data})

    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})


@api_view(['POST'])
def create_message(request):
    try:
        user = request.user
        conversation_id = request.data.get('conversation_id')
        body = request.data.get('body')

        conversation = Conversation.objects.get(id=conversation_id)

        message = Message.objects.create(
            sender=user, body=body)
        conversation.messages.add(message)

        return Response({'status': 'success'})

    except Exception as e:
        return Response({'status': 'error', 'message': str(e)})

src/blog/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from landing.forms import CompleteRegisterForm
from landing.models import CustomUser
from .models import Recipe, Category, Conversation
from .forms import CreateRecipeForm
import json

# Create your views here.


@login_required(login_url='login')
def home(request):

    search = request.GET.get('search', '')

    is_favorite = True if request.path == '/blog/favorites/' else False

    if is_favorite:
        recipes = Recipe.objects.filter(favorites=request.user)

    else:
        recipes = Recipe.objects.filter(
            title__icontains=search) if search else Recipe.objects.all()

    recipes_count = {
        "Breakfast": 0,
        "Lunch": 0,
        "Snack": 0,
        "Dinner": 0,
    }

    for category_name in recipes_count.keys():
        category = Category.objects.filter(name=category_name).first()
        if category:
            recipes_count[category_name] = Recipe.objects.filter(
                categories=category).count()

    duration_count = {
        "15": 0,
        "30": 0,
        "45": 0,
        "60": 0,
    }

    for duration in duration_count.keys():
        duration_count[duration] = Recipe.objects.filter(
            duration__lte=int(duration)).count()

    return render(request, 'blog/home.html', {
        'recipes': recipes,
        'is_favorite': is_favorite,
        'recipes_count': recipes_count,
        'duration_count': duration_count,
    })


@login_required(login_url='login')
def recipe(request, id):
    recipe = Recipe.objects.get(id=id)
    categories = {
        "Breakfast": False,
        "Lunch": False,
        "Snack": False,
        "Dinner": False,
    }

    for category in recipe.categories.all():
        categories[category.name] = True

    ingredients = json.loads(recipe.ingredients)["ingredients"]

    return render(request, 'blog/recipe.html', {
        'recipe': recipe,
        'categories': categories,
        'ingredients': ingredients,
    })


@login_required(login_url='login')
def profile(request, id=None):

    user = request.user if not id else CustomUser.objects.get(id=id)
    user_recipes = Recipe.objects.filter(author=user)

    recipes_count = user_recipes.count()
    favorites_count = user_recipes.filter(favorites=request.user).count()

    likes_received = 0
    for recipe in user_recipes:
        likes_received += recipe.likes_count
    return render(request, 'blog/profile.html', {
        'user': user,
        'user_recipes': user_recipes,
        'recipes_count': recipes_count,
        'favorites_count': favorites_count,
        'likes_received': likes_received,
    })


@login_required(login_url='login')
def edit_profile(request):
    user = request.user
    if request.method == "POST":
        form = CompleteRegisterForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('blog:profile')
    else:
        form = CompleteRegisterForm(instance=user)
    return render(request, 'landing/complete_register.html', {
        'form': form,
        "is_editing": True,
    })


@login_required(login_url='login')
def create_recipe(request):
    if request.method == "POST":
        print(request.POST)
        form = CreateRecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.author = request.user

            recipe.save()

            category_names = request.POST.getlist('categories')
            categories = Category.objects.filter(name__in=category_names)
            recipe.categories.set(categories)

            return redirect('blog:recipe', id=recipe.id)
        else:
            print(form.errors)
    form = CreateRecipeForm()

    return render(request, 'blog/create-recipe.html', {
        'form': form,
    })


def edit_recipe(request, id):

    recipe = Recipe.objects.get(id=id)
    recipe_banner = recipe.banner.url
    form = CreateRecipeForm(instance=recipe)

    if request.method == "POST":
        form = CreateRecipeForm(request.POST, request.FILES, instance=recipe)
        if form.is_valid():
            recipe = form.save(commit=False)

            recipe.save()

            category_names = request.POST.getlist('categories')
            categories = Category.objects.filter(name__in=category_names)
            recipe.categories.set(categories)

            return redirect('blog:recipe', id=recipe.id)
        else:
            print(form.errors)

    return render(request, 'blog/create-recipe.html', {
        'form': form,
        'recipe_banner': recipe_banner,
        'edit': True
    })


@login_required(login_url='login')
def chat(request):

    conversations = Conversation.objects.filter(participant1=request.user) | Conversation.objects.filter(
        participant2=request.user
    )

    active_conversation = request.GET.get('conversation')
    conversation = None
    if active_conversation:
        conversation = Conversation.objects.get(id=active_conversation)

    return render(request, 'blog/chat.html', {
        "conversations": conversations,
        "active_conversation": conversation,
    })

src/blog/templates/blog/chat.html
{% extends "blog_layout.html" %}
{% load static %}
{% block content %}
  <main class="w-full bg-primary px-2 md:px-4 max-w-[1440px] mx-auto h-[calc(100vh-180px)] lg:h-[calc(100vh-150px)] overflow-hidden">
    <section class="w-full grid grid-cols-12 gap-4 h-full">
      {% comment %} Users {% endcomment %}
      <section class="col-span-12 md:col-span-6 pb-[50px] overflow-hidden">
        <div class="text-white flex items-center gap-2 py-2">
          <i class="fa-regular fa-comments fa-xl"></i>
          <h1 class="font-title text-[24px] font-medium">Chat</h1>
        </div>
        <hr>
        <form class="mt-[30px]">
          <div class="bg-[#F2E7D3] flex items-center gap-1">
            <span class=" w-[40px] text-text flex justify-center"><i class="fa-solid fa-magnifying-glass"></i></span>
            <input type="text"
                   name="username"
                   id="search-username"
                   placeholder="Search by username..."
                   class="bg-transparent border-none focus:outline-none font-text font-light  py-3">
          </div>
        </form>
        {% comment %} Chat List {% endcomment %}
        <ul class="mt-[20px] flex flex-col gap-5 h-[75%] overflow-y-scroll scrollbar-thin scrollbar-thumb-white">
          {% if not conversations %}
            <li class="mt-4 text-center w-full flex flex-col items-center justify-center">
              <i class="fa-solid fa-comment-slash fa-2xl"></i>
              <h3 class="mt-4 font-title font-semibold text-[23px] md:text-[26px] lg:text-[30px]">
                You don't have any conversation
              </h3>
              <p class="mt-3 font-text text-white text-[18px] md:text-[20px] lg:text-[22px]">Visit a user's profile and start one</p>
            </li>
          {% else %}
            {% for conversation in conversations %}
              <li>
                <a href="{% url 'blog:chat' %}?conversation={{ conversation.id }}"
                   class="flex items-center gap-2 relative p-2">
                  <div class="bg-blue-400 rounded-full w-[50px] lg:w-[60px] h-[50px] lg:h-[60px]">
                    {% if conversation.participant1 == request.user %}
                      <img src="{{ conversation.participant2.avatar.url }}"
                           alt="chat"
                           width=""
                           height=""
                           class="w-full h-full rounded-full bg-contain">
                    {% else %}
                      <img src="{{ conversation.participant1.avatar.url }}"
                           alt="chat"
                           width=""
                           height=""
                           class="w-full h-full rounded-full bg-contain">
                    {% endif %}
                  </div>
                  <div class="flex flex-col gap-1 max-w-[170px] xs:max-w-[240px] sm:max-w-[400px] md:max-w-[250px] lg:max-w-[370px] xl:max-w-[480px] xxl:max-w-[510px]">
                    <p class="font-title font-bold text-[17px] lg:text-[19px] text-white text-ellipsis overflow-hidden whitespace-nowrap">
                      {% if conversation.participant1 != request.user %}
                        {{ conversation.participant1.name }}
                      {% else %}
                        {{ conversation.participant2.name }}
                      {% endif %}
                    </p>
                    <p class="font-text font-light text-[15px] lg:text-[17px] text-[#F2E7D3] text-ellipsis overflow-hidden whitespace-nowrap">
                      {{ conversation.messages.last.message|truncatechars:30 }}
                    </p>
                  </div>
                </a>
              </li>
            {% endfor %}
          {% endif %}
        </ul>
      </section>
      {% comment %} Conversation {% endcomment %}
      <section id="current-conversation"
               class="absolute md:static z-[10] md:z-0 right-0 top-0 hidden w-full col-span-12 md:col-span-6 h-screen md:h-full bg-background overflow-hidden">
        <div class="w-full h-full relative pb-[150px]">
          <div class="bg-slate-200 w-full p-2 flex items-center gap-3 drop-shadow-md">
            <div class="bg-blue-500 rounded-full h-[60px] w-[60px]">
              {% if active_conversation.participant1 == request.user %}
                <img src="{{ active_conversation.participant2.avatar.url }}"
                     alt="chat"
                     width=""
                     height=""
                     class="w-full h-full rounded-full bg-contain">
              {% else %}
                <img src="{{ active_conversation.participant1.avatar.url }}"
                     alt="chat"
                     width=""
                     height=""
                     class="w-full h-full rounded-full bg-contain">
              {% endif %}
            </div>
            <h3 class="font-title font-medium text-[20px] text-text truncate">
              {% if active_conversation.participant1 != request.user %}
                {{ active_conversation.participant1.name }}
              {% else %}
                {{ active_conversation.participant2.name }}
              {% endif %}
            </h3>
          </div>
          <ul data-user={{ request.user.id }} id="messages-container" class="p-2 mt-5 pb-[110px] md:pb-[50px] flex flex-col gap-7 h-full overflow-y-scroll scrollbar-thin scrollbar-thumb-black">
          </ul>
          <div class="absolute bottom-[74px] md:bottom-0 h-[60px] w-full">
            <section class="w-full h-full">
              <div class="w-full h-full flex items-center justify-between drop-shadow-md">
                <input type="text"
                       name="message"
                       id="message"
                       class="p-2 font-title font-light h-full w-full focus:outline-none"
                       placeholder="Type something...">
                <button type="button"
                        id="send-message"
                        class="w-[70px] h-[60px] bg-accent grid place-content-center">
                  <i class="fa-solid fa-circle-chevron-right fa-xl text-white"></i>
                </button>
              </div>
            </section>
          </div>
        </div>
      </section>
    </section>
  </main>
  <script src="{% static 'scripts/blog/show-conversation.js' %}" type="module"></script>
{% endblock content %}

src/blog/templates/blog/profile.html
{% extends "blog_layout.html" %}
{% load static %}
{% block content %}
  <main class="w-full mb-[100px] max-w-[1440px] mx-auto">
    <section class="mt-5 w-full grid grid-cols-12 gap-y-12 lg:gap-4 xl:gap-5 px-2 lg:px-3 max-w-[600px] mx-auto lg:max-w-none lg:mx-0">
      {% comment %} User info {% endcomment %}
      <section class="px-2 col-span-12 w-full lg:col-span-5 xl:col-span-4 flex flex-col items-center justify-center">
        <div class="w-[160px] h-[160px] border-2 border-primary rounded-full">
          <img src="{{ user.avatar.url }}"
               alt=""
               class="w-full h-full rounded-full object-contain"
               width=""
               height="">
        </div>
        <h3 class="mt-5 font-title font-medium text-[22px] lg:text-[24px] xl:text-[26px]">
          {{ user.name|default:"Anonymous" }}
        </h3>
        <h4 class="mt-2 font-title font-medium text-[18px] lg:text-[19px] xl:text-[20px] text-accent">@{{ user.username }}</h4>
        <div class="mt-4 w-full">
          <div class="flex items-center gap-2">
            <i class="fa-solid fa-circle-info fa-xl text-accent"></i>
            <p class="font-text font-medium text-[19px] lg:text-[21px] xl:text-[23px]">About me</p>
          </div>
          <p class="text-[17px] lg:text-[18px] xl:text-[19px] font-text font-light mt-5 leading-[30px] lg:leading-[32px] xl:leading-[36px] text-justify">
            {% if user.bio %}
              {{ user.bio }}
            {% else %}
              {% if user == request.user %}
                You have not written anything about yourself yet.
              {% else %}
                This user has not written anything about himself yet.
              {% endif %}
            {% endif %}
          </p>
        </div>
        <div class="mt-[40px] py-4 border-y-2 border-y-gray-400 w-full flex flex-col gap-4">
          <div class="w-full flex justify-between items-center">
            <div class="flex items-center gap-2">
              <i class="fa-solid fa-file-circle-plus text-accent fa-xl"></i>
              <span class="text-gray-500 text-[18px] lg:text-[20px]">Published Recipes</span>
            </div>
            <span class="text-accent text-[20px] lg:text-[22px] font-semibold font-logo">{{ recipes_count }}</span>
          </div>
          <div class="w-full flex justify-between items-center">
            <div class="flex items-center gap-2">
              <i class="fa-solid fa-heart text-accent fa-xl"></i>
              <span class="text-gray-500 text-[18px] lg:text-[20px]">Favorites Recipes</span>
            </div>
            <span class="text-accent text-[20px] lg:text-[22px] font-semibold font-logo">{{ favorites_count }}</span>
          </div>
          <div class="w-full flex justify-between items-center">
            <div class="flex items-center gap-2">
              <i class="fa-solid fa-thumbs-up text-accent fa-xl"></i>
              <span class="text-gray-500 text-[18px] lg:text-[20px]">Likes received</span>
            </div>
            <span class="text-accent text-[20px] lg:text-[22px] font-semibold font-logo">{{ likes_received }}</span>
          </div>
          <div class="w-full flex justify-between items-center">
            <div class="flex items-center gap-2">
              <i class="fa-solid fa-calendar text-accent fa-xl"></i>
              <span class="text-gray-500 text-[18px] lg:text-[20px]">Profile created</span>
            </div>
            <span class="text-accent text-[20px] lg:text-[22px] font-semibold font-logo">{{ user.date_joined | date:"d/m/Y" }}</span>
          </div>
        </div>
        <div class="mt-7 lg:w-full">
          {% if user == request.user %}
            <a href="{% url 'blog:edit-profile' %}"
               class="lg:w-[180px] flex items-center justify-center gap-2 bg-primary hover:bg-accent text-white font-semibold text-[18px] transition-colors drop-shadow-md px-2 py-3 md:text-[20px] lg:text-[22px]">
              <i class="fa-solid fa-user-pen fa-lg"></i>
              <span>Edit profile</span>
            </a>
          {% else %}
            <button id="send-message" data-participant={{ user.id }} class="lg:w-[170px] flex items-center justify-center gap-2 bg-primary hover:bg-accent text-white font-semibold text-[18px] transition-colors drop-shadow-md px-2 py-3">
              <i class="fa-regular fa-comments fa-lg"></i>
              <span>Send Message</span>
            </button>
          {% endif %}
        </div>
      </section>
      {% comment %} User recipes {% endcomment %}
      <section class="px-2 col-span-12 lg:col-span-7 xl:col-span-8 max-w-[600px] lg:max-w-none mx-auto flex flex-col w-full items-center lg:items-start">
        <div class="flex items-center gap-2">
          <i class="fa-solid fa-utensils fa-xl text-accent"></i>
          <p class="font-text font-medium text-[23px] sm:text-[25px] lg:text-[27px] xl:text-[28px]">
            {% if user == request.user %}
              My recipes
            {% else %}
              {{ user.username }} recipes
            {% endif %}
          </p>
        </div>
        <section class="mt-5 md:mt-7 w-full grid grid-cols-12 gap-y-8 gap-x-3 max-w-[400px] sm:max-w-[700px] md:max-w-[800px] lg:max-w-none">
          {% if user_recipes %}
            {% for recipe in user_recipes %}
              <article class="recipe-card col-span-12 sm:col-span-6 lg:col-span-6 xl:col-span-4"
                       data-categories="{{ recipe.categories.all|join:", " }}"
                       data-duration="{{ recipe.duration }}">
                <div>
                  <div class="h-[280px] lg:h-[320px] relative">
                    <img src="{{ recipe.banner.url }}"
                         alt="{{ recipe.title }} image"
                         width=""
                         height=""
                         class="w-full h-full absolute top-0">
                    <button id="toggle-favorites"
                            data-recipe="{{ recipe.id }}"
                            class="absolute top-2 right-2 rounded-full p-2 bg-[rgba(0,0,0,0.70)] grid place-content-center text-rose-500 hover:bg-rose-300 transition-colors">
                      <i class="fa-regular fa-heart fa-xl"></i>
                    </button>
                  </div>
                  <a href="{% url 'blog:recipe' recipe.id %}">
                    <div class="mt-4 flex items-center justify-between w-full max-w-[250px]">
                      <div class="flex items-center gap-2 text-gray-400">
                        <i class="fa-regular fa-clock fa-lg"></i>
                        <p class="lg:text-[18px]">{{ recipe.duration }} minutes</p>
                      </div>
                      <div class="flex items-center gap-2 text-gray-400">
                        <i class="fa-regular fa-thumbs-up fa-lg"></i>
                        <p class="lg:text-[18px]">{{ recipe.likes_count }} likes</p>
                      </div>
                    </div>
                    <h4 class="mt-2 text-[20px] font-title font-semibold lg:text-[21px] xl:text-[22px]">{{ recipe.title }}</h4>
                  </a>
                </div>
              </article>
            {% endfor %}
          {% else %}
            <section class="col-span-12 flex flex-col items-center justify-center gap-4">
              <i class="fa-regular fa-folder-open fa-2xl text-text"></i>
              <h3 class="text-[24px] md:text-[26px] lg:text-[28px] font-semibold">There is nothing to show</h3>
              <p class="text-[20px] md:text-[22px] lg:text-[24px] text-gray-400 text-center">
                {% if user == request.user %}
                  You have not created any recipe yet.
                {% else %}
                  This user has not created any recipe yet.
                {% endif %}
              </p>
              {% if user == request.user %}
                <a href="{% url 'blog:create-recipe' %}"
                   class="mt-3 px-2 md:px-3 bg-primary hover:bg-accent transition-colors text-white py-2 font-medium w-auto text-[20px] md:text-[22px] lg:text-[24px] text-center drop-shadow-md">Create Recipe</a>
              {% endif %}
            </section>
          {% endif %}
        </section>
      </section>
    </section>
  </main>
  <script src="{% static 'scripts/blog/toggle-favorites.js' %}" type="module"></script>
  <script src="{% static 'scripts/blog/conversation.js' %}" type="module"></script>
{% endblock content %}